# Generated by Django 5.0.6 on 2024-05-18 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('rated', models.CharField(blank=True, max_length=20, null=True)),
                ('released', models.DateField(blank=True, null=True)),
                ('runtime', models.CharField(blank=True, max_length=10, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
                ('poster', models.URLField(blank=True, null=True)),
                ('meta_score', models.CharField(blank=True, default='0', max_length=20, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('imdb_votes', models.IntegerField(blank=True, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('dvd', models.DateField(blank=True, null=True)),
                ('box_office', models.CharField(blank=True, max_length=50, null=True)),
                ('production', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('genres', models.ManyToManyField(to='app.genre')),
                ('ratings', models.ManyToManyField(to='app.rating')),
            ],
        ),
        migrations.CreateModel(
            name='MovieSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.movie')),
            ],
        ),
        migrations.CreateModel(
            name='UserMovieVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.movieschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
